### ISSUE TITLE
大佬我又来了！

### ISSUE THREAD

**Issue by T8mars** [smthemex/ComfyUI_OmniParser#2]
![image](https://github.com/user-attachments/assets/a2dedbe1-3461-4661-a364-78a85f5287c5)
这是啥问题，模型我也下载了

![image](https://github.com/user-attachments/assets/d53b85e2-7624-40e5-8100-d74fe4a940a8)

**Comment by smthemex** [comment]
要看控制台信息啊，大哥。

**Comment by T8mars** [comment]
对不起我错了
![image](https://github.com/user-attachments/assets/6ed6c42a-235d-428f-bc39-8a7e3f30a032)
![image](https://github.com/user-attachments/assets/0ebb251e-e988-4ade-87a7-3a83f9ff3e1e)

**Comment by T8mars** [comment]
那个路径是添加下载的hf库的路径吗

**Comment by T8mars** [comment]
果然是路径不对，我搞定了。。但是有新的问题，这个EN CH的报错
![image](https://github.com/user-attachments/assets/25d780ca-7c2e-444d-aa8d-0951913828b1)

**Comment by smthemex** [comment]
我改一下代码吧

**Comment by T8star1984** [comment]
谢谢大佬，那个TANGO好像代码公开了，不知道会不会出一个

**Comment by smthemex** [comment]
有人说效果一般，这种热门的会有人去做的

**Comment by T8star1984** [comment]
嗯是的，感谢大佬一直开发好用的节点，真心感谢
